### ISSUE TITLE
Translation of German umlauts isn't displayed properly

### ISSUE THREAD

**Issue by pikim** [pikim/grav-plugin-events#5]
When a month name contains German umlauts, the translation won't be displayed properly. E.g. März: only the first two letters are shown instead of the first 3. When a month name doesn't contain umlauts it works well, see:
![grafik](https://user-images.githubusercontent.com/11775849/74279426-2d701f80-4d1b-11ea-9590-efc000b321a4.png)

**Comment by git-rebug** [comment]
I suppose the problem occurs when umlauts and `substr(...)` meet, so that possibly a _single special character_ takes a _number of characters_ > 1. See also https://www.php.net/manual/en/function.mb-substr.php. The relevant code positions would be the following:

https://github.com/pikim/grav-plugin-events/blob/46d1514fa869f9119028f207d9ff763e0178f3d6/twig/DateTranslationExtension.php#L106

https://github.com/pikim/grav-plugin-events/blob/46d1514fa869f9119028f207d9ff763e0178f3d6/twig/DateTranslationExtension.php#L114

I will probably be able to do some debugging in about a week.

**Comment by pikim** [comment]
It's an issue with `substr`, exactly the way you described it. I replaced `substr` with `mb_substr` and passed `"UTF-8"` as fourth parameter and now it works. It will be contained in the next release.
